name: Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  release:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build release
      run: ./gradlew build
      
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Xiricolico Mod ${{ github.ref_name }}
        body: |
          ## 🎉 Xiricolico Mod ${{ github.ref_name }}
          
          ### 📦 Installation
          1. Download the `.jar` file below
          2. Place it in your `mods` folder
          3. Launch Minecraft with Forge installed
          
          ### 🔧 Requirements
          - Minecraft 1.21+
          - Minecraft Forge 51.0.33+
          - Java 17+
          
          ### 📊 Version Information
          This release follows [Semantic Versioning](https://semver.org/):
          - **MAJOR**: Breaking changes, incompatible API changes
          - **MINOR**: New features, backwards compatible changes
          - **PATCH**: Bug fixes, hotfixes, small improvements
          
          ### 📋 Changelog
          See the commit history and pull requests for detailed changes in this release.
          
          For version increment guidelines, see our [Semantic Versioning Guide](https://github.com/Elfo1507/xiricolico-mod/blob/main/docs/SEMANTIC_VERSIONING.md).
        files: |
          build/libs/*.jar
        draft: false
        prerelease: false
